### ISSUE TITLE
latest data for download is almost 3 months old

### ISSUE THREAD

**Issue by dmgroom** [fossgis/osmdata#7] opened 2020-03-31 14:14 UTC
The latest files for download at https://osmdata.openstreetmap.de/data/coastlines.html are dated 9 January 2020, which is now almost 3 months ago

**Comment by joto** [comment] 2020-03-31 18:18
Yes, this is a known problem. You can see the reason here: https://osmdata.openstreetmap.de/internal/coastline/ . Some mappers have an interesting idea what coastline means, so the coastline has been in the middle of the water for months now. I don't think this is a good idea, so didn't let this change go through.

There was an inconclusive discussion here:
https://lists.openstreetmap.org/pipermail/tagging/2020-January/050252.html

**Comment by landler** [comment] 2020-05-12 11:48
> I don't think this is a good idea, so didn't let this change go through.

Hi, could you explain a bit more what you mean with this? Do you mean that you have selected to completely stop global coastline updates for 4 months due to a local disagreement?

**Comment by joto** [comment] 2020-05-12 12:40
@landler Unfortunately, this is true in a way. The software needs a complete valid set of coastlines. If they are internally consistent, it compares the result with the coastline from the day before and, if it is similar enough, it is automatically validated. This is to prevent small accidents from deleting whole islands or so. This works well automatically unless there is a larger edit, then manual intervention is necessary to make sure the edit was intentional and valid. Now in theory we could have a software that allows changes somewhere else on the planet to go through but not in the disputed area, but in practice we don't have that software. And in theory I had more time to push this issue somewhere and get it resolved, but in practice that's not the case. So we are stuck for the moment unless somebody is willing to invest the time to get this unstuck.

**Comment by landler** [comment] 2020-05-12 12:47
Ok, thanks for clarifying! Would it technically be an option to consider the current state of the coastlines in openstreetmap as valid? i.e. just to understand what the possible avenues for resolution are :)

**Comment by woodpeck** [comment] 2020-05-12 13:00
Main issue is that the OSM community does not agree on how to tag the Rio de la Plata, see discussion https://lists.openstreetmap.org/pipermail/tagging/2020-January/050252.html for background. It would be technically possible to declare the current status "correct" and continue, and things would then freeze again when someone changes the situation around the Rio de la Plata in OSM.

**Comment by landler** [comment] 2020-05-12 13:34
Got it! Is there a reason that wouldn't still be preferable (while obviously sub-optimal) over not having updates to other parts of the world at all anymore? It would at least have the benefit of not having implicitly picked a side in that dispute I guess?
Btw, I appreciate the super quick and informative responses here! :)

**Comment by imagico** [comment] 2020-05-12 13:34
The best approach to resolve this IMO would be to approach the local community in Argentina and Uruguay with the request to discuss their local views of coastline mapping an come up with a set of verifiable consensus principles for that - in general and not specifically for the Rio de la Plata.

The results of this could then either be harmonized with the coastline mapping principles elsewhere to a globally accepted definition or it would be documented as a spatially federated rule set with the rules of coastline mapping in Argentina and Uruguay differing from those elsewhere.

In either case the key is here to produce a clear documentation of verifiable mapping rules that represent the consensus of the local communities.  If such documentation exists it would just be a matter of once checking the coastline is in compliance with these principles.  Unless consensus in the local community changes (which is usually something that does not happen very often) it should be possible to avoid the coastline being stuck as it is right now this way for a longer time since fixing it would just be a matter of restoring the coastline to local community consensus.

Unfortunately doing this would require someone with sufficient knowledge of Spanish to initiate the discussion in the local communities and moderate it to ensure it stays on focus to find a consensus and then write down the results.  That is quite a bit of work.

**Comment by joto** [comment] 2020-05-12 13:55
@imagico I beg to differ. Having every local community define coastline differently doesn't make any sense. I am creating a global coastline file here, if everybody wants to define theirs differently, creating a global one becomes unsustainable and it wouldn't be useful to anybody any more.

But this discussion is becoming off-topic here. Please take all your energy and move the discussion somewhere, where the issue is actually moved forward. Once this is resolved in the OSM community, come back here and I can re-start the coastline processing.

**Comment by joto** [comment] 2020-07-25 08:32
I have now manually "released" the coastline data due to the bad mess we are in right now. But I still have reservation about its correctness, for instance in northern India and on the US east coast. I don't want to be responsible for keeping the coastine mapped correctly and, apparently, nobody else want to be either.

**Closed by joto** 2020-07-25 08:32 UTC
