### ISSUE TITLE
Rio del Plata, oh well...

### ISSUE THREAD

**Issue by kech61** [fossgis/osmdata#10] opened 2020-06-13 18:19 UTC
Hi Jochen,

I know how frustrating the war of mappers can be for people try'in to make real useable datasets and maps out of this pool.
For me as map_renderer its frustrating too to resolve all these self-intersections mappers are placing  in the coastlines no filter can resolve - causing flooded mapsforge maps.
However, there are a lot of people sitting countless hours in front of their monitiors producing better coastlines from new sat_imiges becomming better and better each month - and this work is wasted if you dont prozess the coastlines any more.
The coastline in the middle of the ocean is funny and the monster relation representing the mouth auf the river is a bad joke causing the render to stuck for hours. But this is OSM and if the structure stay as it is without a final court we have to live with this.

Please start your scripts an make a new version of the land-Shapes.
I then will take a look where these silly Intersection are - resolve these in OSM - you make a new Shapefile and we can live for several months with this.

I'm tired to give up against some idiots.

Thanks
Christian
www.openandromaps.org

**Comment by joto** [comment] 2020-06-14 08:31
Duplicate of #7

**Closed by joto** 2020-06-14 08:31 UTC
