### ISSUE TITLE
"404 Not Found" error when trying to download the reduced waterbodies as polygons or as raster masks

### ISSUE THREAD

**Issue by sarope** [fossgis/osmdata#30] opened 2024-07-29 12:52 UTC
Hello, I am working on my master's thesis and it would help me a lot if I could download the data for "Reduced waterbodies as polygons" or "Reduced waterbodies as raster masks" (preferably as polygons). Unfortunately, I get a "404 Not Found" error when trying to download these datasets. Is this something you could help me with? Thank you in advance! Sam

**Comment by joto** [comment] 2024-07-29 14:41
Duplicate of #6.

**Closed by joto** 2024-07-29 14:41 UTC
